### ISSUE TITLE
Data Augumentation

### ISSUE THREAD

**Issue by FeGeyer** [beckstev/MachineLearningSeminar#17]
[Link to class](https://keras.io/preprocessing/image/#imagedatagenerator-class) Ideas: 

- Rotate

- Cropp

- Noise

- Brightness

**Comment by FeGeyer** [comment]
[Used function](https://github.com/keras-team/keras-preprocessing/blob/f16eb5e1801af205f73de64a41af7e90143ac641/keras_preprocessing/image.py#L250)
not the best way, because it rotates first and applies other transformations afterwards, must be changed

**Comment by beckstev** [comment]
See pull request https://github.com/beckstev/MachineLearningSeminar/pull/20
