### ISSUE TITLE
Failure of loading saved models with custom layers/activation_functions

### ISSUE THREAD

**Issue by FeGeyer** [beckstev/MachineLearningSeminar#24]
Wenn wir ein Netzwerk nutzen, welches deine selbstgeschriebene Klasse `PRELU` nutzt, dann gibt es beim ausführen der `predict-Methode` in `evaluate_training` ein Problem bei `model.load`: `ValueError: Unknown layer: PRELU`. Dieses Problem ist bekannt, [siehe](https://github.com/keras-team/keras/pull/6529), was sich laut diesem [Issue](https://github.com/keras-team/keras/issues/7585) auch auf Custom Layer übertragen lässt. Beim Implementieren der Lösung ergab sich das Problem, dass `genetic_utils` nicht importiert werden kann, siehe [hier](https://stackoverflow.com/questions/35905264/keras-importerror-no-module-named-data-utils). Die Lösung dieses Problems bedingt allerdings eine komplette und restlose Deinstallation von alten Keras Versionen, um eine neue installieren zu können.

**Comment by FeGeyer** [comment]
Ich werde mal einen neuen Branch und eine neue virtualenv aufmachen, um ein bisschen rumzuprobieren. Das fixen der Confusion Matrix habe ich mit DogNN getestet, da hier kein `PRELU` verwendet wird.

**Comment by FeGeyer** [comment]
Update: Es ist keine Neuinstallation von keras notwendig. Unsere Installationen von Keras decken das ab, das Modul wurde falschgeschrieben. Richtig wäre `from keras.utils.generic_utils import CustomObjectScope`, dann funktioniert das importieren. Der eigentliche Fehler ist noch nicht behoben.

**Comment by FeGeyer** [comment]
siehe #26

**Comment by beckstev** [comment]
Mit https://github.com/beckstev/MachineLearningSeminar/pull/26 behoben?
>  Der eigentliche Fehler ist noch nicht behoben.

**Comment by FeGeyer** [comment]
Achso, sry, das war nicht eindeutig. Ja der eigentliche Fehler war, dass er bei `model.load` einen Fehler in Bezug auf PReLU geworfen hat. Und das wurde durch #26 behoben.

**Comment by beckstev** [comment]
I also added the `with CustomObjectScope({'PRELU': PReLU()}):` to model loader, which loads the checkpoint model.

**Comment by beckstev** [comment]
Good job!
