### ISSUE TITLE
Do we need a Dataloader?

### ISSUE THREAD

**Issue by beckstev** [beckstev/MachineLearningSeminar#4]
I am not sure if our RAM can handle ~15K images at once. 
So maybe we need a Dataloader which loads all images on the fly.

Check this out: 

https://stanford.edu/~shervine/blog/keras-how-to-generate-data-on-the-fly

**Comment by FeGeyer** [comment]
In der ___data_generation_-Methode müssen wir np.genfromtxt oder das äquivalent von Pandas nutzen, da man mit _np.load_ keine csv Dateien laden kann.

**Comment by beckstev** [comment]
We can use `pandas.read_csv('path_to_file')` .

**Comment by beckstev** [comment]
Implemented
