### ISSUE TITLE
Can we build a CNN with variable input size?

### ISSUE THREAD

**Issue by beckstev** [beckstev/MachineLearningSeminar#5]
There are many posts outthere with this topic, perhaps we find one that we can adapt to your framework. 

Some general information for CNN's: 
https://www.pyimagesearch.com/2018/12/31/keras-conv2d-and-convolutional-layers/

**Comment by FeGeyer** [comment]
Anscheinend bietet es sich an, frühe Lagen von **Conv2D** mit wenigen Filtern auszustatten, und tiefere Lagen mit mehr Filtern auszustatten.

> Layers early in the network architecture (i.e., closer to the actual input image) learn fewer convolutional filters while layers deeper in the network (i.e., closer to the output predictions) will learn more filters.

> Notice at as our output spatial volume is decreasing our number of filters learned is increasing — this is a common practice in designing CNN architectures and one I recommend you do as well.

**Comment by beckstev** [comment]
[Here](https://www.quora.com/How-are-variably-shaped-and-sized-images-given-inputs-to-convoluted-neural-networks) is a general idea why a FCN/CNN can hanlde variable input size.

[Here](https://stackoverflow.com/questions/46204569/how-to-handle-variable-sized-input-in-cnn-with-keras)  is post about how to resize every image of a batch.

**Comment by FeGeyer** [comment]
Ok prinzipiell müssen wir also statt **Flatten()** **GlobalMaxPooling2D()** verwenden. Das habe ich auf nem eigenen Branch auch mal getestet, auf diese Weise kann man ohne Probleme **(None, None, 3)** als Input Shape verwenden. Auf diese Weise kann man auch einen **Dense**-Layer am Ende verwenden, um Klassifikation durchzuführen. Was mir noch nicht ganz klar geworden ist, ob wir trotzdem in jedem Batch die gleiche Größe drin haben müssen. Laut [KeithWM](https://github.com/keras-team/keras/issues/1920) muss das wohl so sein. Stand auch so ähnlich in deiner zweiten Quelle.

**Comment by FeGeyer** [comment]
[Hier](https://keras.io/preprocessing/image/#flow_from_dataframe) gibts ne Möglichkeit Batches mit gleicher Size zu kreieren, und zwar aus einem Dataframe heraus, vorimplementiert von Keras. Allerdings wird das wohl für alle Bilder ausgeführt, die in dem Dataframe sind. Deswegen müssten wir vielleicht, wenn wir nicht alle Bilder gleich resizen wollen, verschiedene Dataframes je nach Bildgröße erstellen

[Hier](https://medium.com/@vijayabhaskar96/tutorial-on-keras-imagedatagenerator-with-flow-from-dataframe-8bd5776e45c1) gibts ein Beispiel zur Anwendung

**Comment by FeGeyer** [comment]
[Hier](https://keras.io/preprocessing/image/#imagedatagenerator-class) ist die Oberklasse, mit der wir auch data augmentation betreiben können (z.B. horizontal oder vertikal flippen, Rotationen etc.) Auch bei Keras als Klasse enthalten.

**Comment by beckstev** [comment]
Implemented a first net
